"""RC column design per IS 456:2000 cl 25, 39, 26.5.3 (+ IS 13920 overlay).

Uniaxial P-M capacity by strain-compatibility integration of the
rectangular-parabolic stress block (cl 38.1 assumptions extended to
compression members per cl 39.1) — the numeric equivalent of SP 16
interaction charts. Biaxial per cl 39.6.

Units: N, mm, MPa internally. Convenience wrappers accept kN, kN.m.
"""

from __future__ import annotations

import math
from dataclasses import dataclass, field

import numpy as np

from .. import tables
from ..materials import Concrete, Steel


@dataclass
class ColumnSection:
    """Rectangular tied column, bars distributed on faces.

    b: width (mm, dimension parallel to bending axis considered),
    D: depth (mm, perpendicular — bending about axis crossing D),
    bars: list of (area_mm2, distance_from_compression_face_mm) — generated by
    `rect_bar_layout` for standard face distributions.
    """
    b: float
    D: float
    fck: float
    fy: float
    bars: list = field(default_factory=list)

    @property
    def Ag(self) -> float:
        return self.b * self.D

    @property
    def Asc(self) -> float:
        return sum(a for a, _ in self.bars)


def rect_bar_layout(b: float, D: float, cover_to_center: float,
                    n_bars: int, bar_dia: float) -> list:
    """Distribute n_bars equally around the perimeter of a rectangular section.

    Returns [(area, y from compression face)] for bending about the axis
    perpendicular to D. n_bars must be even and >= 4.
    """
    if n_bars < 4 or n_bars % 2:
        raise ValueError("n_bars must be even and >= 4")
    area = math.pi * bar_dia ** 2 / 4
    d1, d2 = cover_to_center, D - cover_to_center
    # corner rows always exist; distribute remainder on the two side faces
    per_row = n_bars // 2 if n_bars in (4, 6, 8) and False else None
    bars = []
    # rows: top row, bottom row, plus intermediate rows for bars on side faces
    n_side = (n_bars - 4) // 2 * 2  # bars not in top/bottom rows (pairs)
    n_rows_side = n_side // 2
    bars += [(2 * area, d1), (2 * area, d2)]  # 2 corner bars each row
    extra_top_bottom = n_bars - 4 - n_side
    if extra_top_bottom > 0:  # widen top/bottom rows
        bars[0] = (bars[0][0] + extra_top_bottom / 2 * area, d1)
        bars[1] = (bars[1][0] + extra_top_bottom / 2 * area, d2)
    for i in range(n_rows_side):
        y = d1 + (i + 1) * (d2 - d1) / (n_rows_side + 1)
        bars.append((2 * area, y))
    return bars


# ---------------------------------------------------------------------------
# Sectional capacity — strain compatibility (cl 39.1, 38.1)
# ---------------------------------------------------------------------------

def _concrete_stress(eps: float, fck: float) -> float:
    """Design parabolic-rectangular stress (cl 38.1(c)): peak 0.446 fck at
    strain 0.002, parabolic below."""
    if eps <= 0:
        return 0.0
    if eps >= 0.002:
        return 0.446 * fck
    return 0.446 * fck * (2 * (eps / 0.002) - (eps / 0.002) ** 2)


def section_capacity(sec: ColumnSection, xu: float, n_strips: int = 200) -> tuple:
    """(Pu N, Mu N.mm about centroid) for neutral axis depth xu from the
    compression face. Handles xu > D (NA outside section, cl 39.1(b) pivot)."""
    steel = Steel(sec.fy)
    D, b, fck = sec.D, sec.b, sec.fck
    if xu < 1e-9:
        raise ValueError("xu must be positive")
    if xu >= D:
        # NA outside the section (cl 39.1(b)): the strain profile pivots about
        # 0.002 at 3D/7 from the highly compressed face. With strain zero at
        # the NA (depth xu), the linear profile gives
        # eps(3D/7) = eps_top * (1 - 3D/(7 xu)) = 0.002.
        eps_top = min(0.002 / max(1 - 3 * D / (7 * xu), 1e-9), 0.0035)
        slope = eps_top / xu
        ys = np.linspace(0, D, n_strips)
        eps_c = eps_top - slope * ys
    else:
        eps_top = 0.0035
        slope = eps_top / xu
        ys = np.linspace(0, D, n_strips)
        eps_c = eps_top - slope * ys

    dy = D / (n_strips - 1)
    stresses = np.array([_concrete_stress(e, fck) for e in eps_c])
    forces = stresses * b * dy
    P = forces.sum()
    M = (forces * (D / 2 - ys)).sum()

    for area, y in sec.bars:
        eps_s = eps_top - slope * y
        fs = steel.stress_at_strain(eps_s)
        fc_disp = _concrete_stress(eps_s, fck) if eps_s > 0 else 0.0
        F = (fs - fc_disp) * area
        P += F
        M += F * (D / 2 - y)
    return P, M


def interaction_curve(sec: ColumnSection, n_points: int = 60) -> np.ndarray:
    """Array of (Pu N, Mu N.mm) from pure bending toward pure compression."""
    xus = np.concatenate([
        np.linspace(0.05 * sec.D, sec.D, n_points // 2),
        np.linspace(1.02 * sec.D, 10 * sec.D, n_points // 2),
    ])
    pts = [section_capacity(sec, xu) for xu in xus]
    # anchor: pure axial capacity Puz (cl 39.6 expression)
    puz = 0.45 * sec.fck * (sec.Ag - sec.Asc) + 0.75 * sec.fy * sec.Asc
    pts.append((puz, 0.0))
    return np.array(pts)


def uniaxial_moment_capacity(sec: ColumnSection, Pu_N: float) -> float:
    """Mu1 (N.mm) at a given axial load by interpolating the interaction curve."""
    curve = interaction_curve(sec)
    order = np.argsort(curve[:, 0])
    P_sorted, M_sorted = curve[order, 0], curve[order, 1]
    if Pu_N > P_sorted[-1]:
        return 0.0
    return float(np.interp(Pu_N, P_sorted, np.maximum(M_sorted, 0.0)))


# ---------------------------------------------------------------------------
# Design checks
# ---------------------------------------------------------------------------

@dataclass
class ColumnCheck:
    ok: bool
    checks: list
    data: dict


def design_column(b: float, D: float, fck: float, fy: float,
                  Pu_kN: float, Mux_kNm: float = 0.0, Muy_kNm: float = 0.0,
                  lex: float | None = None, ley: float | None = None,
                  L_unsupported_mm: float | None = None,
                  n_bars: int = 8, bar_dia: float = 20.0,
                  cover: float = 40.0, tie_dia: float = 8.0,
                  seismic: bool = False) -> ColumnCheck:
    """Full column check for a trial reinforcement. All lengths mm.

    lex/ley: effective lengths (mm). Returns pass/fail per clause with data.
    """
    checks, data = [], {}
    Pu = Pu_kN * 1e3
    cc = cover + tie_dia + bar_dia / 2
    Ag = b * D
    area = math.pi * bar_dia ** 2 / 4
    Asc = n_bars * area
    p = 100 * Asc / Ag
    data.update(Ag=Ag, Asc=Asc, p_percent=p)

    # steel limits, cl 26.5.3.1
    checks.append(("min steel 0.8% (cl 26.5.3.1a)", p >= 0.8))
    checks.append(("max steel 6% (4% practical) (cl 26.5.3.1b)", p <= 6.0))
    checks.append(("min 4 bars, dia >= 12 (cl 26.5.3.1c-d)",
                   n_bars >= 4 and bar_dia >= 12))

    # slenderness, cl 25.1.2 / 25.3
    lex = lex or (L_unsupported_mm or 3000.0)
    ley = ley or (L_unsupported_mm or 3000.0)
    slender_x, slender_y = lex / D > 12, ley / b > 12
    data.update(lex_by_D=lex / D, ley_by_b=ley / b,
                slender=slender_x or slender_y)
    checks.append(("slenderness <= 60 (cl 25.3.1)",
                   lex / D <= 60 and ley / b <= 60))

    # minimum eccentricity, cl 25.4
    L = L_unsupported_mm or max(lex, ley)
    ex_min = max(L / 500 + D / 30, 20.0)
    ey_min = max(L / 500 + b / 30, 20.0)
    Mux = max(abs(Mux_kNm) * 1e6, Pu * ex_min)
    Muy = max(abs(Muy_kNm) * 1e6, Pu * ey_min)
    data.update(ex_min=ex_min, ey_min=ey_min)

    # additional moments for slender columns, cl 39.7.1
    puz = 0.45 * fck * (Ag - Asc) + 0.75 * fy * Asc
    data["Puz_kN"] = puz / 1e3
    if slender_x:
        Max = Pu * D / 2000 * (lex / D) ** 2
        k = min(max((puz - Pu) / max(puz - 0.4 * puz, 1e-9), 0.0), 1.0)  # Pb~0.4Puz approx
        Mux += k * Max
        data["Ma_x_kNm"] = k * Max / 1e6
    if slender_y:
        May = Pu * b / 2000 * (ley / b) ** 2
        k = min(max((puz - Pu) / max(puz - 0.4 * puz, 1e-9), 0.0), 1.0)
        Muy += k * May
        data["Ma_y_kNm"] = k * May / 1e6

    # capacity: biaxial interaction, cl 39.6
    sec_x = ColumnSection(b, D, fck, fy, rect_bar_layout(b, D, cc, n_bars, bar_dia))
    sec_y = ColumnSection(D, b, fck, fy, rect_bar_layout(D, b, cc, n_bars, bar_dia))
    Mux1 = uniaxial_moment_capacity(sec_x, Pu)
    Muy1 = uniaxial_moment_capacity(sec_y, Pu)
    data.update(Mux1_kNm=Mux1 / 1e6, Muy1_kNm=Muy1 / 1e6,
                Mux_design_kNm=Mux / 1e6, Muy_design_kNm=Muy / 1e6)
    ratio = Pu / puz
    alpha = 1.0 if ratio <= 0.2 else 2.0 if ratio >= 0.8 else 1.0 + (ratio - 0.2) / 0.6
    data["alpha_n"] = alpha
    if Mux1 <= 0 or Muy1 <= 0:
        interaction = float("inf")
    else:
        interaction = (Mux / Mux1) ** alpha + (Muy / Muy1) ** alpha
    data["interaction"] = interaction
    checks.append(("biaxial interaction <= 1.0 (cl 39.6)", interaction <= 1.0))

    # ties, cl 26.5.3.2(c)
    tie_min = max(bar_dia / 4, 6.0)
    pitch_max = min(min(b, D), 16 * bar_dia, 300.0)
    data.update(tie_dia_min=tie_min, tie_pitch_max=pitch_max)
    checks.append(("tie dia >= max(db/4, 6) (cl 26.5.3.2c-1)", tie_dia >= tie_min))

    # IS 13920 overlay
    if seismic:
        checks.append(("min width 300 for >2 storey support (IS 13920 cl 7.1)",
                       min(b, D) >= tables.DUCTILE["column_min_b_storeys"]))
        lo = max(max(b, D), L / 6, 450.0)
        s_conf = min(tables.DUCTILE["confine_spacing_max"],
                     tables.DUCTILE["confine_spacing_6db"] * bar_dia)
        data.update(confine_length_lo=lo, confine_spacing_max=s_conf)

    return ColumnCheck(all(ok for _, ok in checks), checks, data)
